FROM php:8.2-apache

RUN docker-php-ext-install mysqli

RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    git

RUN docker-php-ext-install zip

COPY . /var/www/html/

EXPOSE 80